
FROM node:16.13.1-alpine3.14

# WORKDIR /usr/src/index

RUN mkdir -p /usr/v1/src/index/app

WORKDIR /usr/v1/src


COPY ["package.json","package-lock.json",".env","./"]

COPY . .

RUN yarn install
 
CMD yarn run dev