# name: NodeJS with Webpack

# on:
#   push:
#     branches: [ "new" ]
#   pull_request:
#     branches: [ "master" ]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [16.x]

#     steps:
#     - uses: actions/checkout@v3

#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v3
#       with:
#         node-version: ${{ matrix.node-version }}

#     - name: Build
#       run: |
#        yarn
#     - name: Build Docker image
#       uses: docker/build-push-action@v2
#       with:
#         context: .
#         push: false
#         tags: my-app:latest





name: Node.js CI/CD Pipeline


on:
  push:
    branches: [ "new" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./Dockerfile
        push: true
        tags: username/repo-name:latest
        dockerfile: Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
    - uses: actions/checkout@v2
    - name: Deploy to production
      run: |
        docker-compose up -d
